# -*- coding: utf-8 -*-
"""PySpark.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13bd5THblRbsIo-MQ9W7x4s04hKCGFP_S
"""

!apt-get install openjdk-8-jdk-headless -qq > /dev/null

!wget https://downloads.apache.org/spark/spark-3.0.1/spark-3.0.1-bin-hadoop2.7.tgz

!tar -xvf spark-3.0.1-bin-hadoop2.7.tgz

!pip install -q findspark

import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.0.1-bin-hadoop2.7"

!pip install pyspark

from pyspark import SparkContext

sc = SparkContext()

rdd = sc.textFile("La+Celestina.txt")

rdd.takeSample(False, 10)

palabras = rdd.flatMap(lambda l: l.split(" ")).map(lambda s: s.strip(".,:;?/_! \(\)\'\"")).countByValue()

palabras

palabras["Celestina"]

palabras["Calisto"]

palabras["Melibea"]

